"""Remove BFL fields and rename Fal fields in AIModel and GeneratedImage

Revision ID: 15a5c33c7946
Revises: 97f6f1a231b3
Create Date: 2025-04-26 16:58:11.742410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15a5c33c7946'
down_revision = '97f6f1a231b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.String(length=120), nullable=True))
        batch_op.drop_index('ix_ai_model_bfl_model_id')
        batch_op.drop_index('ix_ai_model_provider_request_id')
        batch_op.drop_index('ix_ai_model_service_provider')
        batch_op.create_index(batch_op.f('ix_ai_model_request_id'), ['request_id'], unique=False)
        batch_op.drop_column('service_provider')
        batch_op.drop_column('provider_request_id')
        batch_op.drop_column('fal_model_lora_url')
        batch_op.drop_column('bfl_model_id')

    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('download_url', sa.String(length=1024), nullable=True))
        batch_op.drop_index('ix_generated_image_provider_request_id')
        batch_op.create_index(batch_op.f('ix_generated_image_request_id'), ['request_id'], unique=False)
        batch_op.drop_column('provider_download_url')
        batch_op.drop_column('provider_request_id')
        batch_op.drop_column('provider_model_ref')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_model_ref', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.add_column(sa.Column('provider_request_id', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('provider_download_url', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.drop_index(batch_op.f('ix_generated_image_request_id'))
        batch_op.create_index('ix_generated_image_provider_request_id', ['provider_request_id'], unique=False)
        batch_op.drop_column('download_url')
        batch_op.drop_column('request_id')
        batch_op.drop_column('model_url')

    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bfl_model_id', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('fal_model_lora_url', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.add_column(sa.Column('provider_request_id', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('service_provider', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('ix_ai_model_request_id'))
        batch_op.create_index('ix_ai_model_service_provider', ['service_provider'], unique=False)
        batch_op.create_index('ix_ai_model_provider_request_id', ['provider_request_id'], unique=False)
        batch_op.create_index('ix_ai_model_bfl_model_id', ['bfl_model_id'], unique=True)
        batch_op.drop_column('request_id')
        batch_op.drop_column('model_url')

    # ### end Alembic commands ###
