"""Add generation_type and original_url to GeneratedImage

Revision ID: 2956e72469c6
Revises: 8d7c3d256d7a
Create Date: 2025-05-02 20:51:21.538208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2956e72469c6'
down_revision = '8d7c3d256d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        # Комментируем добавление колонок, так как они могут уже существовать
        # batch_op.add_column(sa.Column('generation_type', sa.Enum('TEXT_TO_IMAGE', 'MODEL_PHOTO', 'UPSCALE', name='generationtype'), nullable=False))
        # batch_op.add_column(sa.Column('original_image_url', sa.String(length=512), nullable=True))
        pass # Добавляем pass, если больше ничего не делается в блоке

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        # Комментируем удаление колонок
        # batch_op.drop_column('original_image_url')
        # batch_op.drop_column('generation_type')
        pass # Добавляем pass, если больше ничего не делается в блоке

    # ### end Alembic commands ###
