"""Initial migration for MySQL

Revision ID: 51d1589f780f
Revises: 
Create Date: 2025-04-11 21:00:36.237963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d1589f780f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('subscription_type', sa.Enum('FREE', 'PLUS', 'PREMIUM', name='subscriptiontype'), nullable=False),
    sa.Column('subscription_start_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_stripe_customer_id'), ['stripe_customer_id'], unique=True)

    op.create_table('ai_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bfl_model_id', sa.String(length=120), nullable=True),
    sa.Column('creation_uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('training', 'ready', 'failed', 'pending_deletion', name='modelstatus', native_enum=False), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('eye_color', sa.String(length=30), nullable=True),
    sa.Column('appearance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_model_bfl_model_id'), ['bfl_model_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_model_creation_uuid'), ['creation_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_model_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_model_user_id'), ['user_id'], unique=False)

    op.create_table('generated_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_model_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('camera_angle', sa.String(length=50), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bfl_model_used', sa.String(length=120), nullable=True),
    sa.Column('bfl_request_id', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_model.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_image_ai_model_id'), ['ai_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_image_bfl_request_id'), ['bfl_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_image_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_image_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_image_user_id'))
        batch_op.drop_index(batch_op.f('ix_generated_image_status'))
        batch_op.drop_index(batch_op.f('ix_generated_image_bfl_request_id'))
        batch_op.drop_index(batch_op.f('ix_generated_image_ai_model_id'))

    op.drop_table('generated_image')
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_model_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_model_status'))
        batch_op.drop_index(batch_op.f('ix_ai_model_creation_uuid'))
        batch_op.drop_index(batch_op.f('ix_ai_model_bfl_model_id'))

    op.drop_table('ai_model')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
