"""Increase length of GeneratedImage status column

Revision ID: 7d343ec86de2
Revises: 51d1589f780f
Create Date: 2025-04-12 13:54:57.235000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d343ec86de2'
down_revision = '51d1589f780f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bfl_download_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('local_image_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('is_downloaded', sa.Boolean(), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('is_downloaded')
        batch_op.drop_column('local_image_url')
        batch_op.drop_column('bfl_download_url')

    # ### end Alembic commands ###
