"""Add preview_image_url to AIModel

Revision ID: 887304cb2ac1
Revises: f5d940179086
Create Date: 2025-04-14 20:28:04.749591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887304cb2ac1'
down_revision = 'f5d940179086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_image_url', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.drop_column('preview_image_url')

    # ### end Alembic commands ###
