"""Add payment and paid action models

Revision ID: 8d7c3d256d7a
Revises: 15a5c33c7946
Create Date: 2025-04-26 21:15:25.507160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7c3d256d7a'
down_revision = '15a5c33c7946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paid_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('action_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paid_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paid_action_action_time'), ['action_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_paid_action_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_paid_action_user_id'), ['user_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_points', sa.Integer(), nullable=False),
    sa.Column('payment_time', sa.DateTime(), nullable=True),
    sa.Column('transaction_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_payment_time'), ['payment_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_user_id'), ['user_id'], unique=False)

    # Добавляем создание VIEW вручную (ИСПРАВЛЕННАЯ ВЕРСИЯ)
    op.execute("""
    CREATE VIEW user_balance AS
    WITH user_income AS (
        SELECT
            user_id,
            SUM(amount_points) AS total_income
        FROM
            payment
        WHERE
            status = 'completed'
        GROUP BY
            user_id
    ), user_costs AS (
        SELECT
            user_id,
            SUM(cost_points) AS total_costs
        FROM
            paid_action
        GROUP BY
            user_id
    )
    SELECT
        u.id AS user_id,
        u.email AS user_email,
        COALESCE(i.total_income, 0) - COALESCE(c.total_costs, 0) AS balance_points
    FROM
        `user` u 
    LEFT JOIN
        user_income i ON u.id = i.user_id
    LEFT JOIN
        user_costs c ON u.id = c.user_id;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # СНАЧАЛА удаляем таблицы
    op.drop_table('payment')
    op.drop_table('paid_action')

    # Блоки batch_alter_table для удаления индексов БОЛЬШЕ НЕ НУЖНЫ,
    # так как таблицы уже удалены.
    # with op.batch_alter_table('payment', schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f('ix_payment_user_id'))
    #    batch_op.drop_index(batch_op.f('ix_payment_transaction_id'))
    #    batch_op.drop_index(batch_op.f('ix_payment_status'))
    #    batch_op.drop_index(batch_op.f('ix_payment_payment_time'))

    # with op.batch_alter_table('paid_action', schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f('ix_paid_action_user_id'))
    #    batch_op.drop_index(batch_op.f('ix_paid_action_action_type'))
    #    batch_op.drop_index(batch_op.f('ix_paid_action_action_time'))

    # ### end Alembic commands ###
