"""Add provider_request_id to AIModel

Revision ID: 97f6f1a231b3
Revises: f1dde6faeb21
Create Date: 2025-04-26 16:51:07.065275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f6f1a231b3'
down_revision = 'f1dde6faeb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_request_id', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_model_provider_request_id'), ['provider_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_model_provider_request_id'))
        batch_op.drop_column('provider_request_id')

    # ### end Alembic commands ###
