"""Add service_provider to AIModel

Revision ID: a4616a78617f
Revises: 887304cb2ac1
Create Date: 2025-04-26 16:12:40.323784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4616a78617f'
down_revision = '887304cb2ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_provider', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_ai_model_service_provider'), ['service_provider'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_model_service_provider'))
        batch_op.drop_column('service_provider')

    # ### end Alembic commands ###
