"""Integrate Cloudflare R2 for image storage and update model fields

Revision ID: a540f60bb3e1
Revises: 2956e72469c6
Create Date: 2025-05-09 16:18:59.043021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a540f60bb3e1'
down_revision = '2956e72469c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_r2_object_key', sa.String(length=1024), nullable=True))
        batch_op.drop_column('preview_image_url')

    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('r2_object_key', sa.String(length=1024), nullable=True))
        batch_op.drop_column('local_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_image_url', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.drop_column('r2_object_key')

    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_image_url', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.drop_column('preview_r2_object_key')

    # ### end Alembic commands ###
