"""Add concept_type to AIModel

Revision ID: c3d631742c89
Revises: a540f60bb3e1
Create Date: 2025-05-10 16:45:36.306611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d631742c89'
down_revision = 'a540f60bb3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concept_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.drop_column('concept_type')

    # ### end Alembic commands ###
