"""Add fal_model_lora_url to AIModel and rename fields in GeneratedImage

Revision ID: f1dde6faeb21
Revises: a4616a78617f
Create Date: 2025-04-26 16:27:24.880443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1dde6faeb21'
down_revision = 'a4616a78617f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fal_model_lora_url', sa.String(length=1024), nullable=True))

    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_model_ref', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('provider_request_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('provider_download_url', sa.String(length=1024), nullable=True))
        batch_op.drop_index('ix_generated_image_bfl_request_id')
        batch_op.create_index(batch_op.f('ix_generated_image_provider_request_id'), ['provider_request_id'], unique=False)
        batch_op.drop_column('bfl_download_url')
        batch_op.drop_column('bfl_request_id')
        batch_op.drop_column('bfl_model_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bfl_model_used', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('bfl_request_id', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('bfl_download_url', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.drop_index(batch_op.f('ix_generated_image_provider_request_id'))
        batch_op.create_index('ix_generated_image_bfl_request_id', ['bfl_request_id'], unique=False)
        batch_op.drop_column('provider_download_url')
        batch_op.drop_column('provider_request_id')
        batch_op.drop_column('provider_model_ref')

    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.drop_column('fal_model_lora_url')

    # ### end Alembic commands ###
