"""Add trigger_word to AIModel

Revision ID: f5d940179086
Revises: 7d343ec86de2
Create Date: 2025-04-14 19:57:29.951624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d940179086'
down_revision = '7d343ec86de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_word', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.drop_column('trigger_word')

    # ### end Alembic commands ###
